apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zlb-ingress
  namespace: zlb
  annotations:
    kubernetes.io/ingress.class: nginx 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#    cert-manager.io/cluster-issuer: letsencrypt
#    nginx.ingress.kubernetes.io/cors-allow-credentials: 'true
    kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: '*'
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: "200m"
    nginx.ingress.kubernetes.io/healthcheck-protocol: HTTPS

spec:
  rules:
  - host: zlb.focus.com.tn
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: zlb
            port:
              number: 444
              
